source 'https://rubygems.org'

gem "rake"
gem 'cucumber-api', '~> 0.3'
gem 'nokogiri'

gem 'minke'
gem 'minke-generator-netmvc'

#gem 'minke', :path => '/Users/nicj/Developer/gems/minke'
#gem 'minke-generator-netmvc', :path => '/Users/nicj/Developer/gems/minke-generator-netmvc'
